// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI-uXELAN2B8U253ZNdw817EQKP0VFsZc',
    appId: '1:726899299724:web:14c77370a7ee6b7904f2a9',
    messagingSenderId: '726899299724',
    projectId: 'zegmentdata',
    authDomain: 'zegmentdata.firebaseapp.com',
    storageBucket: 'zegmentdata.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsXGyuoU1gmzF-ngAUDkCMIzi8vzfZeQ',
    appId: '1:726899299724:android:877357edcf3620d104f2a9',
    messagingSenderId: '726899299724',
    projectId: 'zegmentdata',
    storageBucket: 'zegmentdata.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI-uXELAN2B8U253ZNdw817EQKP0VFsZc',
    appId: '1:726899299724:web:14c77370a7ee6b7904f2a9',
    messagingSenderId: '726899299724',
    projectId: 'zegmentdata',
    authDomain: 'zegmentdata.firebaseapp.com',
    storageBucket: 'zegmentdata.appspot.com',
  );
}
